package localhost.abec2304.kurokohi;

public class Operand {
 
    public static final byte
        CONST_S8 = 0,
        CONST_S16 = 1,
        CP_INDEX_U8 = 2,
        CP_INDEX_U16 = 3,
        LV_INDEX_U8 = 4,
        BRANCH_S16 = 5,
        ALIGN4 = 6,
        BRANCH_S32 = 7,
        CONST_S32 = 8,
        ATABLE = 9,
        ALOOKUP = 10,
        NONZERO_U8 = 11,
        ZERO_S8 = 12,
        ATYPE_S8 = 13,
        OPCODE_U8 = 14,
        LV_INDEX_U16 = 15,
        WIDE_IINC_CONST_S16 = 16;
    
    public static final byte[][] TYPE_OF_OPERANDS = {
        /*nop*/null, null/*aconst_null*/,
        /*iconst_m1*/null, null/*iconst_0*/,
        /*iconst_1*/null, null/*iconst_2*/,
        /*iconst_3*/null, null/*iconst_4*/,
        /*iconst_5*/null, null/*lconst_0*/,
        /*lconst_1*/null, null/*fconst_0*/,
        /*fconst_1*/null, null/*fconst_2*/,
        /*dconst_0*/null, null/*dconst_1*/,
        /*bipush*/{CONST_S8}, {CONST_S16}/*sipush*/,
        /*ldc*/{CP_INDEX_U8}, {CP_INDEX_U16}/*ldc_w*/,
        /*ldc2_w*/{CP_INDEX_U16}, {LV_INDEX_U8}/*iload*/,
        /*lload*/{LV_INDEX_U8}, {LV_INDEX_U8}/*fload*/,
        /*dload*/{LV_INDEX_U8}, {LV_INDEX_U8}/*aload*/,
        /*iload_0*/null, null/*iload_1*/,
        /*iload_2*/null, null/*iload_3*/,
        /*lload_0*/null, null/*lload_1*/,
        /*lload_2*/null, null/*lload_3*/,
        /*fload_0*/null, null/*fload_1*/,
        /*fload_2*/null, null/*fload_3*/,
        /*dload_0*/null, null/*dload_1*/,
        /*dload_2*/null, null/*dload_3*/,
        /*aload_0*/null, null/*aload_1*/,
        /*aload_2*/null, null/*aload_3*/,
        /*iaload*/null, null/*laload*/,
        /*faload*/null, null/*daload*/,
        /*aaload*/null, null/*baload*/,
        /*caload*/null, null/*saload*/,
        /*istore*/{LV_INDEX_U8}, {LV_INDEX_U8}/*lstore*/,
        /*fstore*/{LV_INDEX_U8}, {LV_INDEX_U8}/*dstore*/,
        /*astore*/{LV_INDEX_U8}, null/*istore_0*/,
        /*istore_1*/null, null/*istore_2*/,
        /*istore_3*/null, null/*lstore_0*/,
        /*lstore_1*/null, null/*lstore_2*/,
        /*lstore_3*/null, null/*fstore_0*/,
        /*fstore_1*/null, null/*fstore_2*/,
        /*fstore_3*/null, null/*dstore_0*/,
        /*dstore_1*/null, null/*dstore_2*/,
        /*dstore_3*/null, null/*astore_0*/,
        /*astore_1*/null, null/*astore_2*/,
        /*astore_3*/null, null/*iastore*/,
        /*lastore*/null, null/*fastore*/,
        /*dastore*/null, null/*aastore*/,
        /*bastore*/null, null/*castore*/,
        /*sastore*/null, null/*pop*/,
        /*pop2*/null, null/*dup*/,
        /*dup_x1*/null, null/*dup_x2*/,
        /*dup2*/null, null/*dup2_x1*/,
        /*dup2_x2*/null, null/*swap*/,
        /*iadd*/null, null/*ladd*/,
        /*fadd*/null, null/*dadd*/,
        /*isub*/null, null/*lsub*/,
        /*fsub*/null, null/*dsub*/,
        /*imul*/null, null/*lmul*/,
        /*fmul*/null, null/*dmul*/,
        /*idiv*/null, null/*ldiv*/,
        /*fdiv*/null, null/*ddiv*/,
        /*irem*/null, null/*lrem*/,
        /*frem*/null, null/*drem*/,
        /*ineg*/null, null/*lneg*/,
        /*fneg*/null, null/*dneg*/,
        /*ishl*/null, null/*lshl*/,
        /*ishr*/null, null/*lshr*/,
        /*iushr*/null, null/*lushr*/,
        /*iand*/null, null/*land*/,
        /*ior*/null, null/*lor*/,
        /*ixor*/null, null/*lxor*/,
        /*iinc*/{LV_INDEX_U8,CONST_S8}, null/*i2l*/,
        /*i2f*/null, null/*i2d*/,
        /*l2i*/null, null/*l2f*/,
        /*l2d*/null, null/*f2i*/,
        /*f2l*/null, null/*f2d*/,
        /*d2i*/null, null/*d2l*/,
        /*d2f*/null, null/*i2b*/,
        /*i2c*/null, null/*i2s*/,
        /*lcmp*/null, null/*fcmpl*/,
        /*fcmpg*/null, null/*dcmpl*/,
        /*dcmpg*/null, {BRANCH_S16}/*ifeq*/,
        /*ifne*/{BRANCH_S16}, {BRANCH_S16}/*iflt*/,
        /*ifge*/{BRANCH_S16}, {BRANCH_S16}/*ifgt*/,
        /*ifle*/{BRANCH_S16}, {BRANCH_S16}/*if_icmpeq*/,
        /*if_icmpne*/{BRANCH_S16}, {BRANCH_S16}/*if_icmplt*/,
        /*if_icmpge*/{BRANCH_S16}, {BRANCH_S16}/*if_icmpgt*/,
        /*if_icmple*/{BRANCH_S16}, {BRANCH_S16}/*if_acmpeq*/,
        /*if_acmpne*/{BRANCH_S16}, {BRANCH_S16}/*goto*/,
        /*jsr*/{BRANCH_S16}, {LV_INDEX_U8}/*ret*/,
        /*tableswitch*/{ALIGN4,BRANCH_S32,CONST_S32,CONST_S32,ATABLE}, {ALIGN4,BRANCH_S32,CONST_S32,ALOOKUP}/*lookupswitch*/,
        /*ireturn*/null, null/*lreturn*/,
        /*freturn*/null, null/*dreturn*/,
        /*areturn*/null, null/*return*/,
        /*getstatic*/{CP_INDEX_U16}, {CP_INDEX_U16}/*putstatic*/,
        /*getfield*/{CP_INDEX_U16}, {CP_INDEX_U16}/*putfield*/,
        /*invokevirtual*/{CP_INDEX_U16}, {CP_INDEX_U16}/*invokespecial*/,
        /*invokestatic*/{CP_INDEX_U16}, {CP_INDEX_U16,NONZERO_U8,ZERO_S8}/*invokeinterface*/,
        /*invokedynamic*/{CP_INDEX_U16,ZERO_S8,ZERO_S8}, {CP_INDEX_U16}/*new*/,
        /*newarray*/{ATYPE_S8}, {CP_INDEX_U16}/*anewarray*/,
        /*arraylength*/null, null/*athrow*/,
        /*checkcast*/{CP_INDEX_U16}, {CP_INDEX_U16}/*instanceof*/,
        /*monitorenter*/null, null/*monitorexit*/,
        /*wide*/{OPCODE_U8,LV_INDEX_U16,WIDE_IINC_CONST_S16}, {CP_INDEX_U16,NONZERO_U8}/*multianewarray*/,
        /*ifnull*/{BRANCH_S16}, {BRANCH_S16}/*ifnonnull*/,
        /*goto_w*/{BRANCH_S32}, {BRANCH_S32}/*jsr_w*/,
        /*breakpoint*/null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        null, null,
        /*impdep1*/{CONST_S8}, {CONST_S8}/*impdep2*/
    };
    
}
